# Generated by Django 4.2.3 on 2023-07-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description_bis',
            field=models.CharField(default='Pas de description', max_length=100),
        ),
    ]
